name: Auto Unzip

on:
  push:
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Unzip file in root
      run: |
        unzip *.zip
        rm *.zip

    - name: Commit unzipped files
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Unzipped zip file and removed it"
        git push
