name: Unpack WindUI-1.5.4.tar.gz

on:
  push:
    branches:
      - main

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract WindUI-1.5.4.tar.gz
        run: |
          mkdir -p WindUI
          tar -xzf WindUI-1.5.4.tar.gz -C WindUI

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add WindUI
          git commit -m "Unpack WindUI-1.5.4.tar.gz contents"
          git push
