name: Unzip WindUI-1.5.4.zip

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip and flatten folder structure
        run: |
          mkdir -p WindUI
          unzip -o WindUI-1.5.4.zip -d WindUI
          cd WindUI && mv WindUI-1.5.4/* . && rm -r WindUI-1.5.4

      - name: List extracted contents (debugging)
        run: ls -R WindUI

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add WindUI
          git commit -m "Unzip and organize WindUI-1.5.4.zip contents"
          git push
